### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'float' and 'str'

### ISSUE THREAD

**Issue by istar2metal** [hastic/analytics#28]
Using: 
docker-compose build project
grafana 7.1.0
corpglory-hastic-app-0.5.1
hastic/server:latest
hastic/analytics:latest

i got error in analytics log:
```
2021-02-03 08:34:23,794 [Analytics] [ERROR]  handle_analytic_task Exception: 'Traceback (most recent call last):
  File "bin/../analytics/analytic_unit_manager.py", line 89, in handle_analytic_task
    result_payload = await self.__handle_analytic_task(task)
  File "bin/../analytics/analytic_unit_manager.py", line 72, in __handle_analytic_task
    return await worker.do_train(segments, data, payload['cache'])
  File "bin/../analytics/analytic_unit_worker.py", line 42, in do_train
    new_cache: ModelCache = await asyncio.wait_for(self._training_future, timeout = config.LEARNING_TIMEOUT)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 342, in wait_for
    timeout_handle = loop.call_later(timeout, _release_waiter, waiter)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 544, in call_later
    timer = self.call_at(self.time() + delay, callback, *args)
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```
I've tried using different "Detector type" and "Type" while creating "Analytics Unit" in grafana.
Also tried different datasource for metrics: Elasticsearch and prometheus.
Full analytics debug log is attached.
[hastic.log](https://github.com/hastic/analytics/files/5918933/hastic.log)

**Comment by arunbenoyv** [comment]
Is there any solution to this issue. We are also facing the same in our env
With hastic server and analytics version 1.5.1
